### ISSUE TITLE
index.md rules

### ISSUE THREAD

**Issue by americogobbo** [BesrourMS/ethereal#1]
Hi,
I am trying to install your template to use on my website but I am no able to understand the rules that are applied to scrolling the sections.
The index.md is not complete as is in the demo.
Can you help me?
thanks,

**Comment by yuxueyuan** [comment]
I have the same question．
Now I found that maybe the scrolling effect is not possible by using the revised edition of the original theme。Perhaps we have to download the original ethereal theme from [https://html5up.net/ethereal/download](https://html5up.net/ethereal/download) if we want the homepage scroll. @americogobbo
