### ISSUE TITLE
how to create different pages

### ISSUE THREAD

**Issue by bmen** [BesrourMS/ethereal#2]
In the demo it looks like several md files are arranged horizontally next to each other. From the repo is not clear how to do that.

**Comment by wraezor** [comment]
It is not a fully functional port of the HTML5 UP theme.  The theme only includes one panel pulling data from one content file.  It seems like Pico may have the templating ability to make it work as you expect, but the work hasn't been done yet.  If I get some time, I may give it a try.

**Comment by pbw** [comment]
Before I go down a rabbit hole with this identical issue, I'm wondering if anyone has got anywhere with it? Thanks just in case!

**Comment by wraezor** [comment]
I have (slowly) been working on a site with this functionality.  My thought was to have the theme configured with a couple different page styles in a big 'if' structure, then use the appropriate one based on the content file's 'style' defined in metadata.

It's nowhere near polished, but this is where I got to (plus a variety of minor CSS changes to suit my needs).
https://gist.github.com/wraezor/97c957ce3e1a0c7f52c6b3c249900256

**Comment by pbw** [comment]
thanks for posting that @wraezor , I'll take a look..
